version: "3.7"

services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent-nox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul 
      - WEBUI_PORT=8080
      - QBT_WEBUI_PORT=8080
    volumes:
      - /opt/qbittorrent/config:/config 
      - /opt/media:/downloads/media1     
      - /opt/media2:/downloads/media2    
    ports:
      - 8080:8080/tcp       
      - 6881:6881/tcp       
      - 6881:6881/udp       
    restart: unless-stopped
  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000 
    ports:
      - 8096:8096/tcp       
      - 7359:7359/udp       
    volumes:
      - /opt/jellyfin/config:/config  
      - /opt/jellyfin/cache:/cache    
      - type: bind
        source: /opt/media
        target: /media
      - type: bind
        source: /opt/media2
        target: /media2
        read_only: true 
      - type: bind
        source: /path/to/fonts 
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://yourhostadress.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'